require:
- rubocop-performance
AllCops:
  TargetRubyVersion: 2.6.0
Gemspec/RequiredRubyVersion:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Metrics/ClassLength:
  Max: 250
Metrics/CyclomaticComplexity:
  Max: 8
Metrics/MethodLength:
  Max: 15
Metrics/ModuleLength:
  Max: 200
Metrics/ParameterLists:
  Max: 6
Style/DocumentationMethod:
  Enabled: true
Style/SignalException:
  Enabled: false
Layout/LineLength:
  Max: 100

