require:
- rubocop-performance
AllCops:
  TargetRubyVersion: 2.6.0
Gemspec/RequiredRubyVersion:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Metrics/ClassLength:
  Max: 250
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 15
Metrics/ModuleLength:
  Max: 200
Style/DocumentationMethod:
  Enabled: true
Style/SignalException:
  Enabled: false
