name: Slack Bot - Action Ran

on:
  workflow_run:
    workflows:
    - "Commit Checks"
    types:
    - completed

jobs:
  post:
    name: Post Message
    runs-on: ubuntu-latest
    steps:
    - name: Posting
      run: |
        CONCLUSION=$(jq '.workflow_run.conclusion' $GITHUB_EVENT_PATH | tr -d '"')
        LINK_HREF=$(jq '.workflow_run.html_url' $GITHUB_EVENT_PATH | tr -d '"')
        WORKFLOW=$(jq '.workflow_run.name' $GITHUB_EVENT_PATH | tr -d '"')
        REPOSITORY=$(jq '.workflow_run.head_repository.full_name' $GITHUB_EVENT_PATH  | tr -d '"')
        BRANCH=$(jq '.workflow_run.head_branch' $GITHUB_EVENT_PATH | tr -d '"')
        COMMIT=$(jq '.workflow_run.head_sha' $GITHUB_EVENT_PATH | tr -d '"')
        slackMsg() {
          title=$1
          color=$2
          msg="{
            \"channel\":\"gandi_v5\",
            \"attachments\": [
              {
                \"title\":\"$title: $WORKFLOW on $REPOSITORY/$BRANCH\",
                \"title_link\":\"$LINK_HREF\",
                \"text\": \"$GITHUB_ACTOR caused \\\"$WORKFLOW\\\" to run.\n\nCommit: $COMMIT\n$LINK_HREF\",
                \"color\": \"$color\"
              }
            ]
          }"
          echo $msg
          curl -X POST -H "Content-type: application/json; charset=utf-8" -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" -d "$msg" https://slack.com/api/chat.postMessage
        }
        if [ $CONCLUSION = 'success' ]; then
          slackMsg "SUCCESS" "#00FF00"
        elif [ $CONCLUSION = 'cancelled' ]; then
          slackMsg "CANCELLED" "#EE6F47"
        else
          slackMsg "FAILED" "#FF0000"
        fi

